# Auto import pipeline from Google Sheets

schedules:
- cron: "0 * * * *"
  displayName: Hourly import attempt
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    wget https://github.com/Clever/csvlint/releases/download/0.2.0/csvlint-v0.2.0-linux-amd64.tar.gz
    tar zxvf csvlint-v0.2.0-linux-amd64.tar.gz --strip-components 1
    wget -O src/data/devices.csv $DEVICESURL
    ./csvlint src/data/devices.csv || exit 1
    if [ -z "$(git diff src/data)" ]; then
      echo '##vso[task.setvariable variable=dev-diff]skip'
      exit 0
    fi
    git config --local user.name "Azure Pipelines"
    git config --local user.email "azuredevops@microsoft.com"
    git add src/data
    git commit -m "Updating datasets"
  displayName: 'Check for modifications'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(KNOWN_HOST)'
    sshPublicKey: '$(DEPLOY)'
    #sshPassphrase: # Optional
    sshKeySecureFile: deploy_key
    
- script: |
    git remote set-url --push origin git@github.com:blackspherefollower/IoSTIndex
    git push origin HEAD:master
  displayName: 'Publish to GitHub'
  condition: ne(variables['dev-diff'], 'skip')
