# Auto import pipeline from Google Sheets

schedules:
- cron: "0 * * * *"
  displayName: Hourly import attempt
  branches:
    include:
    - master
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    wget -O devices.csv $CSVURL
    if [ -z "$(git diff devices.csv)" ]; then
      echo '##vso[task.setvariable variable=dev-diff]skip'
      exit 0
    fi
    git config --local user.name "Azure Pipelines"
    git config --local user.email "azuredevops@microsoft.com"
    git add devices.csv
    git commit -m "Updating devices.csv"
  displayName: 'Check for modifications'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(KNOWN_HOST)'
    sshPublicKey: '$(DEPLOY)'
    #sshPassphrase: # Optional
    sshKeySecureFile: deploy_key
    
- script: |
    git remote set-url --push origin git@github.com:blackspherefollower/IoSTIndex
    git push origin HEAD:master
  displayName: 'Publish to GitHub'
  condition: ne(variables['dev-diff'], 'skip')
