version: 2.0

jobs:
  build:
    docker:
        - image: circleci/node:lts
    steps:
      - checkout # check out the code in the project directory
      - run: wget -O src/data/devices.csv ${DEVICESURL}
      - run: git config --local user.name "CircleCI"
      - run: git config --local user.email "circleci@circleci.com"
      - run: git add src/data
      - run: git commit -m "Updating datasets"

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
